import { Button, Container, Grid, Text } from "@nextui-org/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Learning from "../public/font.svg";
import { SectionOne } from "../components/home/SectionOne";
import { Landing } from "../components/home/Landing";
import { Footer } from "../components/home/Footer";
import { SectionTwo } from "../components/home/SectionTwo";

const Home: NextPage = () => {
  return (
    <>
      <div className={styles.container} style={{ padding: 0 }}>
        <Head>
          <title>OpenLanguage</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Landing Screen */}
        <Landing />

        {/*========== BODY ========== */}
        <div
          style={{ backgroundColor: "white", height: "100vh", width: "100vw" }}
        >
          <Container
            css={{
              paddingTop: 20,
              height: "30em",
              "@sm": {
                padding: 0,
              },
              "@md": {
                paddingRight: "10em",
                paddingLeft: "10em",
              },
              "@lg": {
                paddingRight: "10em",
                paddingLeft: "10em",
              },
            }}
          >
            <SectionOne />
            <SectionTwo />

            <Footer />
          </Container>
        </div>
      </div>
    </>
  );
};

export default Home;
